# yaml-language-server: $schema=https://json-schema.org/draft-07/schema

title: Networking config schema

$defs:
  nodepattern:
    type: string
    pattern: ^N\d$
  wirepattern:
    type: string
    pattern: ^W\d$

properties:
  nodes:
    type: object
    patternProperties:
      ^N\d$:
        type: object
        properties:
          MAC:
            $ref: "#/$defs/nodepattern"
          IP:
            type: number
            minimum: 0x0
            exclusiveMaximum: 0x100
          wire:
            $ref: "#/$defs/wirepattern"
        additionalProperties: false
        required:
          - MAC
          - IP
          - wire
    additionalProperties: false
  wires:
    type: object
    patternProperties:
      ^W\d$:
        type: number

additionalProperties: false
