# yaml-language-server: $schema=https://json-schema.org/draft-07/schema

title: Networking config schema

$defs:
  nodepattern:
    type: string
    pattern: ^N\d$

properties:
  nodes:
    type: object
    patternProperties:
      ^N\d$:
        type: object
        properties:
          MAC:
            $ref: "#/$defs/nodepattern"
          IP:
            type: number
            minimum: 0x0
            exclusiveMaximum: 0x100
          port:
            type: number
        additionalProperties: false
        required:
          - MAC
          - IP
          - port
    additionalProperties: false
  wires:
    type: array
    items:
      type: object
      properties:
        nodes:
          type: array
          items:
            $ref: "#/$defs/nodepattern"

additionalProperties: false
