# yaml-language-server: $schema=./config-schema.yaml

nodes:
  N1:
    MAC: N1
    IP: 0x11
    wire: W0
  N2:
    MAC: N2
    IP: 0x22
    wire: W0
  N3:
    MAC: N3
    IP: 0x23
    wire: W0

wires:
  W0: 8000
