# yaml-language-server: $schema=./config-schema.yaml

config:
  HOSTNAME: 127.0.0.1
  LOGGING_LEVEL: DEBUG
  RECEIVE_SIZE: 1000
  SOCKET_TIMEOUT: 1

nodes:
  N1:
    MAC: N1
    IP: 0x12
    wire: W0
  N2:
    MAC: N2
    IP: 0x13
    wire: W0
  N3:
    MAC: N3
    IP: 0x23
    wire: W0

wires:
  W0: 8000
